
- name: Setup repositories using Subscription Manager for engine
  hosts: ovirt_engines
  remote_user: root
  vars_files:
    - secrets.yml
  vars:
    ovirt_repositories_use_subscription_manager: True
    ovirt_repositories_ovirt_version: 4.4-beta
    ovirt_repositories_target_host: engine
    ovirt_repositories_pool_ids:
      - 8a99f9a86fe87e7f016feb6faaf91813
      - 8a99f9a271e672dc0172098df3dc09dc 
  roles:
    - role: ovirt.repositories

- name: Setup repositories using Subscription Manager for hosts
  hosts: ovirt_hosts
  remote_user: root
  vars_files:
    - secrets.yml
  vars:
    ovirt_repositories_use_subscription_manager: True
    ovirt_repositories_ovirt_version: 4.4-beta
    ovirt_repositories_target_host: host
    ovirt_repositories_pool_ids:
      - 8a99f9a86fe87e7f016feb6faaf91813
      - 8a99f9a271e672dc0172098df3dc09dc
  roles:
    - role: ovirt.repositories

